### ISSUE TITLE
Unexpected token . 

### ISSUE THREAD

**Issue by phucvo0709** [vercel/next-plugins#411] opened 2019-02-25 09:47 UTC
I have the same error with many plugins how to fix?

![untitled](https://user-images.githubusercontent.com/35060381/53328595-eb3cab00-391c-11e9-9d40-e92d00b3e8aa.png)

this config

```
const withCSS = require('@zeit/next-css');
const withSass = require('@zeit/next-sass');
const withLess = require('@zeit/next-less');
// const nextConfig = require('next/webpack.config')

module.exports = withLess(withSass(withCSS({
    webpack: config => {
        // Fixes npm packages that depend on `fs` module
        config.node = {
            fs: 'empty'
        };
        config.module.rules.push({ test: /\.(png|woff|woff2|eot|ttf|svg|gif)$/, loader: 'url-loader?limit=100000' });

        return config
    }
})));
```

**Comment by piuccio** [comment] 2019-04-16 04:42
Duplicate of #261 maybe?

**Comment by tenjojeremy** [comment] 2020-04-30 17:21
Hey @phucvo0709, did you find a solution for this?

**Comment by timneutkens** [comment] 2020-12-18 07:23
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.

**Closed by timneutkens** 2020-12-18 07:23 UTC
