### ISSUE TITLE
next-css doesn't support server side rendering

### ISSUE THREAD

**Issue by hanford** [vercel/next-plugins#1] opened 2018-02-05 21:56 UTC
In [this small repo](https://github.com/hanford/nextjs-cssmodules) I've illustrated `next-css` not working with SSR, this is a blocker from my team moving off of https://github.com/traveloka/styled-modules which we're super eager to do.

Great work on Next.js 5.0! Can't wait to fully migrate to it :)

I would mind if Next.js apps had to have a custom `_document.js` to support this, but I guess thats more of an implementation detail.

**Comment by ScottPolhemus** [comment] 2018-02-05 23:44
Noticed this as well. As a temporary workaround for this, it's possible to disable the `ExtractTextPlugin` after it's been added by `next-css` via your `next.config.js`:
```
const withCSS = require('@zeit/next-css');
const ExtractTextPlugin = require('extract-text-webpack-plugin')

module.exports = withCSS({
  webpack: (config) => {
    config.plugins = config.plugins.map((p) => {
      if (p instanceof ExtractTextPlugin) {
        p.options.disable = true
      }
      return p
    })
    
    return config
  },
})
```

**Comment by Jarred-Sumner** [comment] 2018-02-05 23:57
Running into this issue as well

**Comment by ScottPolhemus** [comment] 2018-02-06 00:04
As far as I can tell, there are two issues preventing the extract plugin from working as intended:
1. The CSS file is extracted to `/.next/static/style.css`, but static files aren't served from that directory or copied to the output folder when using the `extract` command. Moving the file to to `/static/style.css` (relative to the project root) would resolve that issue.
2. In the SSR/static export environment, you will need a `<style>` tag that references the CSS file somewhere in your app's `<head>`. This could be accomplished by adding some code to a custom document component (`/pages/_document.js`), which may or may not be within the scope of the plugin. For example this would include the appropriate style tag outside the dev environment:
```
<Head>
  {!this.props.dev && (
    <link rel="stylesheet" href={`${this.props.__NEXT_DATA__.assetPrefix}/static/style.css`} />
  )}
</Head>
```

**Comment by timneutkens** [comment] 2018-02-06 10:17
@ScottPolhemus https://github.com/zeit/next-plugins/tree/master/packages/next-css#production-usage

**Comment by flipxfx** [comment] 2018-02-06 14:36
Having this issue also. Any CSS file that I import causes the FOUC.

**Comment by ScottPolhemus** [comment] 2018-02-06 16:51
@timneutkens This is great, thanks! Those instructions work well for SSR, so I think the only remaining issue is that the `/.next/static` directory is not copied to the output folder when running `next export`.

For anyone following along, this just means you'll need to run `cp -r .next/static out/_next` after `next export` for this to work with the static export function currently (replacing `out` with your output folder if you specified one for `export`).

**Comment by thomaslindstrom** [comment] 2018-02-06 23:09
Running `next build && next start` with `cssModules` enabled – the generated class names do not match the HTML/JS output.

**Comment by timneutkens** [comment] 2018-02-07 07:16
I’ve made a PR for SSR support btw 👍🏻

**Comment by maeertin** [comment] 2018-02-08 10:26
I seem to be experiencing the same issue as @thomaslindstrom. Any luck with that?

**Comment by huangbong** [comment] 2018-02-18 00:00
For those that are reading this after version 0.1.0 (when https://github.com/zeit/next-plugins/pull/50 got merged), you no longer need to do what @ScottPolhemus is suggesting with `!this.props.dev`. After 0.1.0 the style.css file is now also generated in dev mode so you can just put a `<link rel='stylesheet' href='/_next/static/style.css' />` in `_document.js` and you should be good to go in both dev and prod without FOUC. Thanks to @timneutkens for the PR!

**Comment by Ehesp** [comment] 2018-02-18 10:55
Subbing to this. The following doesn't work:

```
module.exports = withCss(
  withLess({
    cssModules: true,
  })
);
```

Removing `withCss` wrapper and it works fine, just I'm trying to pull in some external css from node_modules.

**Comment by Marvin1003** [comment] 2018-03-02 08:47
I am experiencing an issue where my external css file doesnt get updated on client side page transitions. It only works flawless on ssr. What could cause this issue? Only way to get it properly working for me at the moment is to prefetch every css file.

**Comment by Ehesp** [comment] 2018-03-06 09:29
@hanford have you had a chance to see if the PR works for you?

**Comment by crushy26** [comment] 2018-03-09 17:35
@Ehesp Did you get that it working?

**Comment by emyann** [comment] 2018-03-13 19:32
On my side I didn't get it working 😕 I ended up with my own `withSass` Next plugin 
![enable-sass-next](https://user-images.githubusercontent.com/4748419/37365096-dc492e78-26d2-11e8-965c-4f661126901f.png)

How I configure it:

```
const sassConfig = withSass({
      sassLoaderOptions: {
        includePaths: ['styles', 'node_modules']
          .map(d => path.join(__dirname, d))
          .map(g => glob.sync(g))
          .reduce((a, c) => a.concat(c), [])
      }
    })
```

Then how I use it in my app

![enable-sass-next-document](https://user-images.githubusercontent.com/4748419/37365285-6d4ae74a-26d3-11e8-8413-b249ca367b92.png)

I sill have a specific rule to handle my css files

```
      config.module.rules.push({
        test: /\.css$/,
        use: ['babel-loader', 'raw-loader', 'postcss-loader']
      })
```

**Comment by prabu-ramaraj** [comment] 2018-04-13 01:55
@Marvin1003 - Did you fix this? I am having same problem with next-sass. Client side transitions are not loading the updated style.css file. I have to reload the whole page in order to update the style.css file.

**Comment by Marvin1003** [comment] 2018-04-13 09:33
@prabu-ramaraj sadly no. 
I use external styled components now with which i can approach the same.

**Comment by krokhale** [comment] 2018-04-23 04:30
Just referencing this issue: https://github.com/zeit/next.js/issues/4184

**Comment by breeswish** [comment] 2018-07-13 08:16
Nearly half a year.. Any updates about this "OMG Maximum" priority issue?

**Comment by revskill10** [comment] 2019-01-16 08:43
I got this error when exporting a NextJS app with Antd + Less.

**Comment by stephankaag** [comment] 2019-03-07 10:39
@timneutkens Any clue where to start?

**Comment by timneutkens** [comment] 2019-03-07 10:53
You'll probably want to use https://github.com/zeit/styled-jsx#styles-in-regular-css-files instead of next-css.

**Comment by tuckerconnelly** [comment] 2019-06-13 19:55
I was able to get this working using styled-jsx plugins. This example is for antd, probably similar for others:

`.babelrc`
```js
{
  "presets": [
    [
      "next/babel",
      {
        "styled-jsx": {
          "plugins": ["styled-jsx-plugin-less"]
        }
      }
    ]
  ]
}
```

`next.config.js`
```js
module.exports = {
  webpack: (config, { defaultLoaders }) => {
    config.module.rules.push({
      test: /\.less/,
      use: [
        defaultLoaders.babel,
        {
          loader: require('styled-jsx/webpack').loader,
          options: {
            type: 'global'
          }
        }
      ]
    });

    return config;
  }
};
```

`_document.js`
```js
import React from 'react';
import Document, { Html, Head, Main, NextScript } from 'next/document';

import antdCustom from '../antd-custom.less';

class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const initialProps = await Document.getInitialProps(ctx);
    return { ...initialProps };
  }

  render() {
    return (
      <Html>
        <Head>
          <style>{`body { margin: 0 } /* custom! */`}</style>
          <meta
            name="viewport"
            content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"
          />
          <meta name="apple-mobile-web-app-capable" content="yes" />
          <style>{antdCustom}</style>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```

`antd-custom.less`
```css
@import 'node_modules/antd/dist/antd.less';

@primary-color: #1890ff;
```

**Comment by 1337-x** [comment] 2019-08-25 22:00
I'm new to next-css. What  exactly is wrong with server-side rendering and this plugin?

**Comment by timneutkens** [comment] 2020-12-18 07:38
Hi, thanks for creating an issue. We currently recommend using nextjs.org/docs/basic-features/built-in-css-support as the plugins have been deprecated in favor of the built-in support.

**Closed by timneutkens** 2020-12-18 07:38 UTC
Labels: enhancement
